name: Keep Supabase Alive

on:
  schedule:
    - cron: '0 9 * * 1,4' # Segunda e quinta às 09:00 UTC
  workflow_dispatch:      # Permite execução manual

jobs:
  ping-api:
    runs-on: ubuntu-latest

    steps:
      - name: Pingar rota de keep-alive
        env:
          HOST: ${{ secrets.HOST }}
        run: |
          echo "Pinging ${HOST}/api/ping..."
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$HOST/api/ping")

          if [ "$STATUS" -ne 200 ]; then
            echo "Erro: Status $STATUS ao pingar $HOST/api/ping"
            exit 1
          else
            echo "Ping bem-sucedido! Status: $STATUS"
          fi
